Form validation and error handling
tanadendere/jet-set-journey pull request #6
Opened 2024-05-09 08:22 UTC by tanadendere

- Implemented form validation to ensure data integrity and prevent submission of invalid input for login, register as well as adding trips and itinerary items.
- Added state management to check if a user's email already exists before allowing registration 
- Added state management for user existence validation during login to ensure only registered users can access the system.

2024-05-09 16:49 UTC, Musa-Mabasa commented on src/app/components/home/add-trip/add-trip.component.html
> +    <button type="submit" [disabled]="!form.valid">Create trip</button>
You can use `form.invalid` here

2024-05-09 17:18 UTC, Musa-Mabasa commented on src/app/userManagement/components/register/register.component.ts
> +        matchingPaaswordControl!.errors &&
Avoid assertions here. Do an if check on `matchingPasswordControl`

2024-05-09 17:19 UTC, Musa-Mabasa commented on src/app/userManagement/components/register/register.component.ts
> +      if (passwordControl!.value !== matchingPaaswordControl!.value) {
Same thing here with the assertion

2024-05-09 17:25 UTC, Musa-Mabasa requested changes
I left some suggestion comments. I request a change with the assertions. Either than that, everything else is good 👍

2024-05-10 08:02 UTC, Musa-Mabasa commented on src/app/userManagement/components/register/register.component.ts
> +      if (matchingPaaswordControl && passwordControl) {
🫡

2024-05-10 08:02 UTC, Musa-Mabasa approved these changes
Everything looks good 👍

2024-05-10 14:22 UTC, yanevdw approved these changes
Amazing job Tana! Your validation and error handling is exceptional.

2024-05-10 14:22 UTC, yanevdw commented on src/app/userManagement/components/login/login.component.ts
> +    ],
Nice!

2024-05-10 14:22 UTC, yanevdw commented on src/app/userManagement/components/register/register.component.html
> +        allowed.
Great error handling here!

2024-05-10 15:02 UTC, merged